# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9hcjvODOenXtWmDBc5IQZD6gVXH5d_K
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

base = pd.read_csv('credit_data.csv')

base

base.head(10)

base.tail(10)

base.info()

base.describe() #Dá uma descrição da base

base['income'].mean(), base['income'].min(), base['income'].median() #Média dos valores e o valor mínimo, e mediana

sns.countplot(x = base['default'])

plt.hist( x = base['income']) #Quantas pessoas ganham tal valor, em dezenas de milhares
#No gráfico

plt.hist(x = base['age']) #Quantas pessoas tem tal idade, em dezenas, no gráfico

grafico = px.scatter_matrix(base, dimensions=['income', 'age', 'loan'], color = 'default')
grafico.show()

base.loc[base['age'] < 0] # Foca no Id do dataframe

base[base['age'] < 0]

base2 = base

#Apagar a coluna
#base2 = base2.drop('age', axis = 1)
#Apagar os registros com problema
#base2 = base2.drop(base2[base2['age']<0].index)
#base2[base2['age']<0]
#base['age'].mean()
#base['age'][base2['age']>0].mean() #pega a médias das idades maior que 0
base2.loc[base2['age']<0, 'age'] = base2['age'][base2['age']>0].mean()

base2.head(16)

base2.isnull().sum() #Soma os nulos para verificar quais são nulos

base2.loc[pd.isnull(base2['age'])]

base2['age'].fillna(base2['age'].mean(), inplace = True) #Aplica na própria coluna por conta do inplace
#se não precisaria de um base2 =, no começo